/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by CppSharp.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */

public class CppData {
    private long nativeInstanceAddr;
    private boolean ownsNativeInstance;

    private native void createInstanceJni();
    public CppData()
    {
        createInstanceJni();
    }

    private native void destroyInstanceJni();

    public void close()
    {
        if (!ownsNativeInstance)
        {
            return;
        }

        if (nativeInstanceAddr == 0)
        {
            return;
        }

        destroyInstanceJni();
    }

    private native boolean getBoolJni();
    public boolean getBool()
    {
        return getBoolJni();
    }

    private native void setBoolJni(boolean value);
    public void setBool(boolean value)
    {
        setBoolJni(value);
    }
}
