/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by CppSharp.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */

public class CppData {
    private long nativeInstanceAddr;
    private boolean ownsNativeInstance;

    private native void createInstanceJni();
    public CppData()
    {
        createInstanceJni();
    }

    private native void destroyInstanceJni();

    public void close()
    {
        if (!ownsNativeInstance)
        {
            return;
        }

        if (nativeInstanceAddr == 0)
        {
            return;
        }

        destroyInstanceJni();
    }

    private native boolean getBoolJni();
    public boolean getBool()
    {
        return getBoolJni();
    }

    private native void setBoolJni(boolean value);
    public void setBool(boolean value)
    {
        setBoolJni(value);
    }

    private native byte getInt8Jni();
    public byte getInt8()
    {
        return getInt8Jni();
    }

    private native void setInt8Jni(byte value);
    public void setInt8(byte value)
    {
        setInt8Jni(value);
    }

    private native byte getUint8Jni();
    public byte getUint8()
    {
        return getUint8Jni();
    }

    private native void setUint8Jni(byte value);
    public void setUint8(byte value)
    {
        setUint8Jni(value);
    }

    private native short getInt16Jni();
    public short getInt16()
    {
        return getInt16Jni();
    }

    private native void setInt16Jni(short value);
    public void setInt16(short value)
    {
        setInt16Jni(value);
    }

    private native short getUint16Jni();
    public short getUint16()
    {
        return getUint16Jni();
    }

    private native void setUint16Jni(short value);
    public void setUint16(short value)
    {
        setUint16Jni(value);
    }

    private native int getInt32Jni();
    public int getInt32()
    {
        return getInt32Jni();
    }

    private native void setInt32Jni(int value);
    public void setInt32(int value)
    {
        setInt32Jni(value);
    }

    private native int getUint32Jni();
    public int getUint32()
    {
        return getUint32Jni();
    }

    private native void setUint32Jni(int value);
    public void setUint32(int value)
    {
        setUint32Jni(value);
    }

    private native long getInt64Jni();
    public long getInt64()
    {
        return getInt64Jni();
    }

    private native void setInt64Jni(long value);
    public void setInt64(long value)
    {
        setInt64Jni(value);
    }

    private native long getUint64Jni();
    public long getUint64()
    {
        return getUint64Jni();
    }

    private native void setUint64Jni(long value);
    public void setUint64(long value)
    {
        setUint64Jni(value);
    }

    private native float getFloatJni();
    public float getFloat()
    {
        return getFloatJni();
    }

    private native void setFloatJni(float value);
    public void setFloat(float value)
    {
        setFloatJni(value);
    }

    private native double getDoubleJni();
    public double getDouble()
    {
        return getDoubleJni();
    }

    private native void setDoubleJni(double value);
    public void setDouble(double value)
    {
        setDoubleJni(value);
    }

    private native boolean getPubBoolJni();
    public boolean getPubBool()
    {
        return getPubBoolJni();
    }

    private native void setPubBoolJni(boolean value);
    public void setPubBool(boolean value)
    {
        setPubBoolJni(value);
    }

    private native byte getPubI8Jni();
    public byte getPubI8()
    {
        return getPubI8Jni();
    }

    private native void setPubI8Jni(byte value);
    public void setPubI8(byte value)
    {
        setPubI8Jni(value);
    }

    private native byte getPubU8Jni();
    public byte getPubU8()
    {
        return getPubU8Jni();
    }

    private native void setPubU8Jni(byte value);
    public void setPubU8(byte value)
    {
        setPubU8Jni(value);
    }

    private native short getPubI16Jni();
    public short getPubI16()
    {
        return getPubI16Jni();
    }

    private native void setPubI16Jni(short value);
    public void setPubI16(short value)
    {
        setPubI16Jni(value);
    }

    private native short getPubU16Jni();
    public short getPubU16()
    {
        return getPubU16Jni();
    }

    private native void setPubU16Jni(short value);
    public void setPubU16(short value)
    {
        setPubU16Jni(value);
    }

    private native int getPubI32Jni();
    public int getPubI32()
    {
        return getPubI32Jni();
    }

    private native void setPubI32Jni(int value);
    public void setPubI32(int value)
    {
        setPubI32Jni(value);
    }

    private native int getPubU32Jni();
    public int getPubU32()
    {
        return getPubU32Jni();
    }

    private native void setPubU32Jni(int value);
    public void setPubU32(int value)
    {
        setPubU32Jni(value);
    }

    private native long getPubI64Jni();
    public long getPubI64()
    {
        return getPubI64Jni();
    }

    private native void setPubI64Jni(long value);
    public void setPubI64(long value)
    {
        setPubI64Jni(value);
    }

    private native long getPubU64Jni();
    public long getPubU64()
    {
        return getPubU64Jni();
    }

    private native void setPubU64Jni(long value);
    public void setPubU64(long value)
    {
        setPubU64Jni(value);
    }

    private native float getPubF32Jni();
    public float getPubF32()
    {
        return getPubF32Jni();
    }

    private native void setPubF32Jni(float value);
    public void setPubF32(float value)
    {
        setPubF32Jni(value);
    }

    private native double getPubF64Jni();
    public double getPubF64()
    {
        return getPubF64Jni();
    }

    private native void setPubF64Jni(double value);
    public void setPubF64(double value)
    {
        setPubF64Jni(value);
    }
}
